version: '3'

services:
  web:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - .:/code
    # command: gunicorn censo.wsgi:application --reload --bind 0.0.0.0:1337 --workers 1 --log-level INFO --timeout 300
