version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["gunicorn", "censo.wsgi:application", "--reload", "--bind", "0.0.0.0:1337", "--workers", "1", "--log-level", "INFO", "--timeout", "300"]
    container_name: censo
    volumes:
      - .:/censo
    ports:
      - "8001:8001"
